title: Jinyu Tong's Homepage
page-top-title: Jinyu Tong
top-section-bg-text: Toward autonomous ocean exploration
home-subtitle: Jinyu Tong&ensp;|&ensp;童金宇
copyright-text: '&copy; Jinyu Tong 2026. All Rights Reserved.'
