title: Jinyu Tong's Homepage
page-top-title: Jinyu Tong
top-section-bg-text: Full Stack Developer & Engineer
home-subtitle: Jinyu Tong&ensp;| &ensp; 童金宇
copyright-text: '&copy; Jinyu Tong 2026. All Rights Reserved.'
